### ISSUE TITLE
Schedule: CSS needs needs one more style

### ISSUE THREAD

**Issue by melloware** [primefaces/primefaces-showcase#287]
Currently the themes style...

```css
body .fc .fc-event {
    background: #E3F2FD;
    border: 1px solid #E3F2FD;
    color: #495057;
}
```

But they need to also add `.fc-v-event .fc-event-main`...
```css
body .fc .fc-event,
body .fc-v-event .fc-event-main {
    background: #E3F2FD;
    border: 1px solid #E3F2FD;
    color: #495057;
}
```

See (the white text get washed out):
![image](https://user-images.githubusercontent.com/4399574/104817275-4c5e1800-57ee-11eb-9ce5-7902739dc74a.png)
